// Generated by mochi - Do not edit manually
// https://github.com/qwexvf/mochi

/** Represents nullable values */
export type Maybe<T> = T | null | undefined;

/** Represents a list that may contain null items */
export type MaybeList<T> = Maybe<Maybe<T>[]>;

export type Scalars = {
  ID: string;
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  /** Custom scalar - extend as needed */
  DateTime: string;
  /** Custom scalar - extend as needed */
  JSON: Record<string, unknown>;
};

/** The category of a move */
export enum MoveCategory {
  /** Uses Attack and Defense stats */
  PHYSICAL = "PHYSICAL",
  /** Uses Special Attack and Special Defense stats */
  SPECIAL = "SPECIAL",
  /** Does not deal damage directly */
  STATUS = "STATUS",
}

/** The elemental type of a Pokemon */
export enum PokemonType {
  BUG = "BUG",
  DARK = "DARK",
  DRAGON = "DRAGON",
  ELECTRIC = "ELECTRIC",
  FAIRY = "FAIRY",
  FIGHTING = "FIGHTING",
  FIRE = "FIRE",
  FLYING = "FLYING",
  GHOST = "GHOST",
  GRASS = "GRASS",
  GROUND = "GROUND",
  ICE = "ICE",
  NORMAL = "NORMAL",
  POISON = "POISON",
  PSYCHIC = "PSYCHIC",
  ROCK = "ROCK",
  STEEL = "STEEL",
  WATER = "WATER",
}

/** A move that a Pokemon can learn */
export interface Move {
  /** Accuracy percentage */
  accuracy?: Maybe<Scalars["Int"]>;
  category: MoveCategory;
  description: Scalars["String"];
  id: Scalars["Int"];
  name: Scalars["String"];
  /** Base power (null for status moves) */
  power?: Maybe<Scalars["Int"]>;
  /** Power Points */
  pp: Scalars["Int"];
  /** The elemental type of this move */
  type: PokemonType;
}

/** A Pokemon creature */
export interface Pokemon {
  /** The Pokemon this one evolves into */
  evolvesTo?: Maybe<Pokemon>;
  /** Height in meters */
  height: Scalars["Float"];
  id: Scalars["Int"];
  /** Moves this Pokemon can learn */
  moves: Move[];
  /** The name of this Pokemon */
  name: Scalars["String"];
  /** National Pokedex number */
  pokedexNumber: Scalars["Int"];
  /** URL to the Pokemon's sprite image */
  spriteUrl: Scalars["String"];
  /** Base stats */
  stats: Stats;
  /** The elemental type(s) of this Pokemon */
  types: PokemonType[];
  /** Weight in kilograms */
  weight: Scalars["Float"];
}

/** Base stats of a Pokemon */
export interface Stats {
  /** Physical attack power */
  attack: Scalars["Int"];
  /** Physical defense */
  defense: Scalars["Int"];
  /** Hit Points */
  hp: Scalars["Int"];
  /** Special attack power */
  specialAttack: Scalars["Int"];
  /** Special defense */
  specialDefense: Scalars["Int"];
  /** Speed determines turn order */
  speed: Scalars["Int"];
  /** Total of all base stats */
  total: Scalars["Int"];
}

/** A Pokemon trainer */
export interface Trainer {
  /** Number of gym badges earned */
  badges: Scalars["Int"];
  id: Scalars["Int"];
  name: Scalars["String"];
  /** Number of Pokemon caught */
  pokedexCaught: Scalars["Int"];
  /** The trainer's Pokemon team */
  team: Pokemon[];
}

export interface QueryMoveArgs {
  /** Move ID */
  id: Scalars["Int"];
}

export interface QueryPokemonArgs {
  /** Pokemon ID */
  id: Scalars["Int"];
}

export interface QueryPokemonByNameArgs {
  /** Pokemon name */
  name: Scalars["String"];
}

export interface QueryPokemonByTypeArgs {
  /** Pokemon type to filter by */
  type: PokemonType;
}

export interface QueryTrainerArgs {
  /** Trainer ID */
  id: Scalars["Int"];
}

export interface Query {
  /** Get all moves */
  allMoves: Move[];
  /** Get all Pokemon */
  allPokemon: Pokemon[];
  /** Get all trainers */
  allTrainers: Trainer[];
  /** Get a move by ID */
  move(args: QueryMoveArgs): Maybe<Move>;
  /** Get a Pokemon by ID */
  pokemon(args: QueryPokemonArgs): Maybe<Pokemon>;
  /** Get a Pokemon by name */
  pokemonByName(args: QueryPokemonByNameArgs): Maybe<Pokemon>;
  /** Get all Pokemon of a specific type */
  pokemonByType(args: QueryPokemonByTypeArgs): Pokemon[];
  /** Get a trainer by ID */
  trainer(args: QueryTrainerArgs): Maybe<Trainer>;
}